/** Single source of truth: sheet tab names and header row order (row 1 in Google Sheet). */

export const SHEET_NAMES = {
  Leads: "Leads",
  Users: "Users",
  Partners: "Partners",
  Countries: "Countries",
  Source_Managers: "Source_Managers",
  Partner_Managers: "Partner_Managers",
  Statuses: "Statuses",
  Audit_Log: "Audit_Log",
  Telegram_Log: "Telegram_Log",
  System_Settings: "System_Settings",
  Views_Config: "Views_Config",
  Dashboard_Cache: "Dashboard_Cache",
} as const;

export type SheetName = (typeof SHEET_NAMES)[keyof typeof SHEET_NAMES];

export const HEADERS = {
  Leads: [
    "lead_id",
    "crm_deal_id",
    "created_at",
    "updated_at",
    "created_by_user_id",
    "updated_by_user_id",
    "created_by_role",
    "country_code",
    "country_name",
    "partner_id",
    "partner_name",
    "partner_manager_name",
    "source_manager_id",
    "source_manager_name",
    "client_name",
    "client_phone",
    "client_email",
    "client_language",
    "service_type",
    "source_channel",
    "transfer_status",
    "partner_status",
    "final_outcome",
    "lead_priority",
    "sent_to_partner_at",
    "partner_accepted_at",
    "partner_rejected_at",
    "first_contact_at",
    "in_progress_at",
    "proposal_sent_at",
    "contract_signed_at",
    "closed_lost_at",
    "last_update_at",
    "contract_amount_local",
    "contract_currency",
    "fx_rate_to_usd",
    "contract_amount_usd",
    "commission_percent",
    "commission_amount_local",
    "commission_amount_usd",
    "manager_comment",
    "partner_comment",
    "rejection_reason",
    "loss_reason",
    "is_archived",
    "tags",
    "hidden_meta_json",
  ],
  Users: [
    "user_id",
    "full_name",
    "login",
    "password",
    "role",
    "is_active",
    "token_hash",
    "token_last_rotated_at",
    "token_expires_at",
    "partner_id",
    "source_manager_id",
    "allowed_country_codes",
    "allowed_partner_ids",
    "telegram_chat_id_optional",
    "dashboard_preset_json",
    "created_at",
    "updated_at",
  ],
  Partners: [
    "partner_id",
    "partner_name",
    "country_code",
    "country_codes",
    "source_manager_ids",
    "active_flag",
    "owner_name",
    "telegram_bot_token",
    "telegram_chat_id",
    "notification_enabled",
    "default_currency",
    "notes",
  ],
  Countries: [
    "country_code",
    "country_name",
    "local_currency",
    "fx_rate_to_usd",
    "active_flag",
  ],
  Source_Managers: [
    "source_manager_id",
    "source_manager_name",
    "active_flag",
    "country_scope",
    "partner_scope",
  ],
  Partner_Managers: [
    "partner_manager_id",
    "partner_id",
    "partner_manager_name",
    "active_flag",
  ],
  Statuses: [
    "category",
    "status_code",
    "status_label",
    "status_description",
    "sort_order",
    "is_final",
    "active_flag",
    "color",
  ],
  Audit_Log: [
    "log_id",
    "timestamp",
    "lead_id",
    "user_id",
    "user_name",
    "user_role",
    "action_type",
    "field_name",
    "old_value",
    "new_value",
    "comment",
    "ip_optional",
    "user_agent_optional",
  ],
  Telegram_Log: [
    "telegram_log_id",
    "timestamp",
    "lead_id",
    "partner_id",
    "recipient_chat_id",
    "message_text",
    "status",
    "error_message",
  ],
  System_Settings: ["key", "value", "comment"],
  Views_Config: [
    "config_id",
    "user_id",
    "role",
    "config_key",
    "config_json",
    "updated_at",
  ],
  Dashboard_Cache: ["cache_key", "payload_json", "updated_at"],
} as const;

export function rowToObject<T extends Record<string, string>>(
  headers: readonly string[],
  row: string[],
): T {
  const o = {} as Record<string, string>;
  headers.forEach((h, i) => {
    o[h] = row[i] ?? "";
  });
  return o as T;
}

export function objectToRow(
  headers: readonly string[],
  obj: Record<string, string>,
): string[] {
  return headers.map((h) => {
    const v = obj[h];
    if (v == null || v === "") return "";
    return typeof v === "string" ? v : String(v);
  });
}
